server:
  port: 9090
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: captain-service
          uri: lb://CAPTAIN-SERVICE
          predicates:
            - Path=/api/captains/**
        - id: rider-service
          uri: lb://RIDER-SERVICE
          predicates:
            - Path=/api/riders/**
        - id: ride-management-service
          uri: lb://RIDE-MANAGEMENT-SERVICE
          predicates:
            - Path=/api/rides/**
        # - id: rider-service
        #   uri: lb://RIDER-SERVICE
        #   predicates:
        #     - Path=/api/riders/**

            
    #TODO: Add JWT filter config here
