# spring:
#   profiles:
#     active: default
#   cloud:
#     config:
#       uri: http://localhost:8080  # Config Server URL
#   application:
#     name: ${spring.application.name}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
