spring:
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888  # Config Server URL
  application:
    name: ${spring.application.name}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka Server URL

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
