server:
  port: 8082

spring:
  application:
    name: captain-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/captain-service
    username: postgres
    password: patelji
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect




queue-count: 5
ride-offer:
  exchange: ride.offer.exchange
  queues-prefix: captain.group.
  routing-key-prefix: key.captain.group.


  
# driver:
#   verification:
#     enabled: true
#   max-active-rides: 3

