server:
  port: 8081

spring:
  application:
    name: rider-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rider-service
    username: postgres
    password: patelji
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

ride:
  base-fare: 5.00 
  per-kilometer-rate: 2.50


ride-management-service:
  url: http://localhost:9090/api/captains
